name: Process Images
on:
  pull_request:
    paths:
      - 'public/img/**'
jobs:
  build:
    name: sharp
    runs-on: ubuntu-latest
    if: github.event.pull_request.head.repo.fork == false
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Cache dependencies
        uses: actions/cache@v4
        id: cache
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-primes-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-primes-
      - name: Install dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: npm ci
      - name: ✧ Process images and Report results
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_REPOSITORY: ${{ github.repository }}
          GITHUB_PULL_REQUEST: ${{ toJSON(github.event.pull_request) }}
        run: npm run process-images
